#!/bin/sh
# http://openlgtv.org.ru - LGMOD
# Copyright 2009 Vuk
# Copyright 2010 Arno1
# Copyright 2011 lprot, mmm4m5m

CFG_DIR="/mnt/lg/user/lgmod"

START() {
	echo "djmount: $@"
	[ -d /sys/module/fuse ] || modprobe fuse.ko
	if [ -n "$2" ]; then
		djmount -f -o kernel_cache "$2" &
	else
		[ -f $CFG_DIR/upnp ] || { echo "djmount: File not found: $CFG_DIR/upnp"; return 1; }
		djmount -f -o kernel_cache `cat $CFG_DIR/upnp` &
	fi
}

boot() {
	{
	# Launch UPnP client
	[ -e $CFG_DIR/upnp ] && START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	pgrep -f '^djmount ' && { echo 'djmount: Already started'; return 1; }
	START "$@"
}

stop() {
	pkill -f '^djmount '
}

restart() {
	stop "$@"; START "$@"
}

case "$1" in
	boot)		boot "$@";;
	start)		start "$@";;
	stop)		stop "$@";;
	restart)	restart "$@";;
	*)			echo "Usage: $0 start|stop|restart [DIR]"; exit 1
esac
