#!/bin/sh
# Source code released under GPL License
# rcS for Saturn7 by mmm4m5m

CFG_DIR="/mnt/lg/user/lgmod"

START() {
	echo "dropbear: $@"
	[ ! -f /etc/dropbear/dropbear_rsa_host_key ] && [ ! -f /etc/dropbear/dropbear_dss_host_key ] && {
		echo 'dropbear: RSA/DSS host keys not found. Please use: dropbearkey'
		echo 'dropbear: help: dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key'
		echo 'dropbear: help: dropbearkey -t rsa -f /etc/dropbear/dropbear_dss_host_key'
		echo 'dropbear: help: Add your pub key to /mnt/lg/user/root/.ssh/authorized_keys'
		return 1; }
	. /etc/init.d/rcS-devrw
	[ -f /sbin/modprobe ] && modprobe=modprobe || modprobe=insmod
	[ -d /sys/module/pty ] ||
		$modprobe /lib/modules/pty.ko
	f=$CFG_DIR/ssh; [ -f $f ] && dropbear $(cat $f) || dropbear
}

boot() {
	{
	# Launch SSH server
	[ -f $CFG_DIR/ssh ] && START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	pgrep -f '^dropbear ' && { echo 'dropbear: Already started'; return 1; }
	START "$@"
}

stop() {
	pkill -f '^dropbear '
}

restart() {
	stop "$@"; START "$@"
}

case "$1" in
	boot)		boot "$@";;
	start)		start "$@";;
	stop)		stop "$@";;
	restart)	restart "$@";;
	*)			echo "Usage: $0 start|stop|restart"; exit 1
esac
