#!/bin/sh
# http://openlgtv.org.ru - LGMOD
# Copyright 2009 Vuk
# Copyright 2010 Arno1
# Copyright 2011 lprot, mmm4m5m

START() {
	CFG_DIR="/mnt/lg/user/lgmod"
	MODULES_SH=$CFG_DIR/module.sh
	SRC_DIR=/home/lgmod

	# lgmod: rc.sysinit rc.local
	# Copy script for modules loading if not exist (first boot)
	if [ ! -e $MODULES_SH ]; then
		echo "module: Default ${MODULES_SH##*/} ..."
		[ -d "$CFG_DIR" ] || mkdir -p "$CFG_DIR"; # first boot?
		cp -a $SRC_DIR/default-${MODULES_SH##*/} $MODULES_SH; sync
	fi
	# Load modules with modules script
	if [ -x $MODULES_SH ]; then
		echo "module: $@ ${MODULES_SH##*/} ..."
		(
		cd /lib/modules/2.6.26; CONV_MODSH=''
		if [ ! -d /mnt/lg/lginit ]; then # S6
			# file path were included in old module.sh
			insmod() {
				local mf m="${1#/modules/}"; mf="/lib/modules/2.6.26/$m"
				if [ "$m" = "$1" ]; then # not old module.sh
					/sbin/insmod "$@"
				else
					CONV_MODSH=1
					if [ -f "$mf" ]; then # old module.sh
						shift; /sbin/insmod "$mf" "$@"
					else modprobe "${m%.ko}" "$@"; fi
				fi; }
		fi
		. $MODULES_SH "$@"
		[ -n "$CONV_MODSH" ] && { sed -i -e 's#[ \t]/modules/# #g' $MODULES_SH; sync; }
		)
	fi
}

boot() {
	{
	START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	START "$@"
}

case "$1" in
	boot)		boot "$@";;
	start)		start "$@";;
	*)			echo "Usage: $0 start"; exit 1
esac
