#!/bin/sh
# http://openlgtv.org.ru - LGMOD
# Copyright 2009 Vuk
# Copyright 2010 Arno1
# Copyright 2011 lprot, mmm4m5m

CFG_DIR="/mnt/lg/user/lgmod"
FS_MNT=$CFG_DIR/ndrvtab

START() {
	if [ -f $FS_MNT ]; then
		. /etc/init.d/rcS-funcs; # load_modules
		cat $FS_MNT | while read ndrv; do
			automount="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			[ "$automount" = "1" ] || continue
			fs_type="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			src="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			dst="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			[ -d "$dst" ] || continue
			opt="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			uname="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			pass="${ndrv%%#*}"; #ndrv="${ndrv#*#}"
			mnt_opt='noatime';
			[ "$uname" ] && mnt_opt="${mnt_opt},user=$uname,pass=$pass"
			[ "$opt" ] && mnt_opt="${mnt_opt},${opt}"
			echo "mount: $1 $mnt_opt $src $dst ..."
			load_modules "mount: $1" "$fs_type" &&
				mount -t "$fs_type" -o "$mnt_opt" "$src" "$dst"
		done
	fi
}

boot() {
	{
	# After network is configured, network services can be started
	START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	START "$@"
}

stop() {
	if [ -f $FS_MNT ]; then
		sync
		ARG=''; [ "$2" != '-f' ] && [ "$2" != '-r' ] || ARG="$2"
		grep -n '' $FS_MNT | sort -nr | cut -d':' -f 2- | while read ndrv; do
			automount="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			[ "$automount" = "1" ] || continue
			fs_type="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			src="${ndrv%%#*}"; ndrv="${ndrv#*#}"
			dst="${ndrv%%#*}"; #ndrv="${ndrv#*#}"
			[ -d "$dst" ] || continue
			D=$(stat -c%D $dst/.. $dst); n=$'\n'
			[ "${D%%$n*}" = "${D#*$n}" ] && continue
			echo "mount: $1 $ARG $dst ..."
			umount $ARG "$dst"
		done
	fi
}

restart() {
	stop "$@"; START "$@"
}

case "$1" in
	boot)		boot "$@";;
	start)		start "$@";;
	stop)		stop "$@";;
	restart)	restart "$@";;
	*)			echo "Usage: $0 start|stop|restart [-f|-r]"; exit 1
esac
