#!/bin/sh
#
# /etc/init.d/rcK - run once at shutdown

#!/bin/sh
# Source code released under GPL License
# rcS for Saturn6/Saturn7 by mmm4m5m

if [ -d /mnt/lg/lginit ]; then # not S6 = S7
	RELBIN='^/mnt/lg/lgapp/RELEASE '; # pgrep
else
	RELBIN='./RELEASE'; # pgrep
fi

# Note: 'netcast' removed from rootfs-S6
for i in lgmod netcast mount release-mount; do
	# TODO: use sym.links /etc/rc.d/[SK]*
	[ -f /etc/init.d/$i ] && . /etc/init.d/$i stop
done

sync

if ! cat /proc/mounts | grep -q ' cramfs '; then
	# LG inittab
	/bin/umount -a -r
#elif pgrep -f "$RELBIN"; then
#	# LG inittab
#	/bin/umount -a -r
else
	umount -r $(cat /proc/mounts|grep -nv ' / \| cramfs '|sort -nr|cut -d' ' -f2)
fi

echo 'rcK: shutdown DONE'
exit 0
