#!/bin/sh
## /etc/init.d/rcS - run once at boot time
#. /etc/rc.d/rc.sysinit
#. /etc/rc.d/rc.local

#!/bin/sh
# LGMOD version ver=
# Source code released under GPL License
# lginit/rcS for Saturn7 by mmm4m5m

trap 'RCS_BREAK_CTRL_C=1' INT; # requre: ttyS0::sysinit:...

# config values: empty or non-empty
RCS_CHROOT=''; #sdb1/lgmod_s7.sqf
RCS_OVERLAY=''
RCS_OVERLAY_ONCE=''
USB=/tmp/lgmod/Chrusb; CHR=/tmp/lgmod/Chroot
BOOTMOD=/mnt/lg/user/lgmod/boot

DIR=/mnt/lg/lginit; MNT=/mnt/lg/user; OUT=/dev/kmsg
CHRI=/tmp/lgmod/chroot; CHRO=/tmp/lgmod/overlay; # lginit
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /etc/init.d/rcS-tmpfs

D=$(stat -c%D / $MNT); n=$'\n'; [ "${D%%$n*}" = "${D#*$n}" ] &&
	. /etc/init.d/rcS-lguser > $OUT 2>&1; # rcS-lginit

if [ -f "$BOOTMOD" ]; then
	echo "rcS: Found $BOOTMOD" > $OUT; . "$BOOTMOD"
	[ -n "$RCS_OVERLAY_ONCE" ] && { RCS_OVERLAY="$RCS_OVERLAY_ONCE"; sed -ie '/^RCS_OVERLAY_ONCE=/d' "$BOOTMOD" > $OUT 2>&1; }
	[ -n "$RCS_OVERLAY_ONCE" ] && sync > $OUT 2>&1
fi


DEV="/dev/${RCS_CHROOT%%/*}"; SQF="$USB/${RCS_CHROOT#*/}"
if [ -n "$RCS_CHROOT" ] && [ -b "$DEV" ]; then
	#. /etc/init.d/rcS-tmpfs
	if mkdir -p "$USB" > $OUT 2>&1; then
		echo "rcS: trying $DEV $SQF ..." > $OUT
		. /etc/init.d/rcS-usercall1 call_and_wait > $OUT 2>&1
		if mount -t vfat -o iocharset=utf8,shortname=mixed,noatime "$DEV" "$USB" > $OUT 2>&1 ||
			mount -t ntfs -o noatime "$DEV" "$USB" > $OUT 2>&1; then
			if [ -f "$SQF" ]; then
				if mkdir -p "$CHR" > $OUT 2>&1 &&
					mount -t squashfs "$SQF" "$CHR" > $OUT 2>&1 &&
					mount -o bind $DIR "$CHR$DIR" > $OUT 2>&1; then
					{ echo "rcS: chroot $SQF ..."; mount -o bind /tmp "$CHR/tmp"
					mount -o bind / "$CHR$CHR"; mount -o bind "$USB" "$CHR$USB"
					mount -o bind $MNT "$CHR$MNT"
					[ -d "$CHRI" ] && mount -o bind "$CHRI" "$CHR$CHRI"
					[ -d "$CHRO" ] && mount -o bind "$CHRO" "$CHR$CHRO"
					} > $OUT 2>&1
					exec chroot "$CHR" sh /etc/init.d/rcS-overlay "$RCS_OVERLAY" chroot
					{ echo "rcS: Error $?"
					[ -d "$CHRO" ] && umount "$CHR$CHRO"; [ -d "$CHRI" ] && umount "$CHR$CHRI"
					umount "$CHR$MNT" "$CHR$USB" "$CHR$CHR" "$CHR/tmp"; } > $OUT 2>&1
				fi; { umount "$CHR$DIR"; umount "$CHR" && sleep 1 && rm -rf "$CHR"; } > $OUT 2>&1
			else echo "rcS: Error chroot $SQF" > $OUT
			fi; umount "$USB" > $OUT 2>&1
fi; fi; fi


. /etc/init.d/rcS-overlay "$RCS_OVERLAY"

exec sh
exit 1
