#!/bin/sh
# Source code released under GPL License
# lginit/rcS for Saturn7 by mmm4m5m

OUT=/dev/kmsg

{
if [ ! -d /proc/bus/usb ]; then
	mount -t proc proc /proc
	mount -t sysfs sysfs /sys
	mount -t usbfs usbfs /proc/bus/usb
	mount -t tmpfs tmpfs /tmp -o size=24M
fi
} > $OUT 2>&1
