#!/bin/sh
# Source code released under GPL License
# rcS for Saturn6/Saturn7 by mmm4m5m

if [ "$1" != 1 ]; then
	# LG rc.local
	if [ ! -d /mnt/lg/lginit ]; then # S6
		APP_XIP=`cat /proc/xipfs`
		FONT_XIP=`cat /proc/fontxipfs`
	else # S7
		APP_XIP=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/appxip_addr=/ { print $2 }'`
		FONT_XIP=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/fontxip_addr=/ { print $2 }'`
	fi
else
	if [ ! -d /mnt/lg/lginit ]; then # S6
		I='1'; # ugly?
	else # S7
		I='2 3 4 5'
	fi
	CMD=''

	APP_XIP=''; ADDR=''
	for i in $I; do
		if [ $i = 3 ] || [ $i = 4 ]; then [ -z "$CMD" ] && CMD=" $(cat /proc/cmdline) "; fi
		if   [ $i = 1 ]; then addr=''; f=/proc/xipfs; [ -e $f ] && addr=`cat $f`; # S6
		elif [ $i = 2 ]; then addr="$appxip_addr"; # kernel/init export
		elif [ $i = 3 ]; then addr="${CMD#*appxip_addr=}"; addr="${addr%% *}"; # kernel first cmd line arg
		elif [ $i = 4 ]; then addr="${CMD##*appxip_addr=}"; addr="${addr%% *}"; # kernel last cmd line arg
		elif [ $i = 5 ]; then addr=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/appxip_addr=/ { print $2 }'`; # S7 LG rc.local
		else break; fi; [ "$addr" = "$ADDR" ] && continue; ADDR="$addr"; # skip if already checked
		if [ "$addr" != "" ] && [ "$addr" != "0x0" ]; then
			cramfs_magic=`devmem $((addr+16)) 64`
			release_magic=`devmem $((addr+1024*4)) 32`
			if [ "$cramfs_magic" != '0x73736572706D6F43' ]; then
				echo "rcS-cramfs($i): Error: cramfs lgapp_xip - wrong magic"
			elif [ "$release_magic" != '0x464C457F' ]; then
				echo "rcS-cramfs($i): Error: cramfs RELEASE - wrong magic"
			else APP_XIP="$addr"; export appxip_addr="$addr"; break; fi
		fi
	done

	FONT_XIP=''; ADDR=''
	for i in $I; do
		if [ $i = 3 ] || [ $i = 4 ]; then [ -z "$CMD" ] && CMD=" $(cat /proc/cmdline) "; fi
		if   [ $i = 1 ]; then addr=''; f=/proc/fontxipfs; [ -e $f ] && addr=`cat $f`; # S6
		elif [ $i = 2 ]; then addr="$fontxip_addr"; # kernel/init export
		elif [ $i = 3 ]; then addr="${CMD#*fontxip_addr=}"; addr="${addr%% *}"; # kernel first cmd line arg
		elif [ $i = 4 ]; then addr="${CMD##*fontxip_addr=}"; addr="${addr%% *}"; # kernel last cmd line arg
		elif [ $i = 5 ]; then addr=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/fontxip_addr=/ { print $2 }'`; # S7 LG rc.local
		else break; fi; [ "$addr" = "$ADDR" ] && continue; ADDR="$addr"; # skip if already checked
		if [ "$addr" != "" ] && [ "$addr" != "0x0" ]; then
			cramfs_magic=`devmem $((addr+16)) 64`
			if [ "$cramfs_magic" != '0x73736572706D6F43' ]; then
				echo "rcS-cramfs($i): Error: cramfs lgfont_xip - wrong magic"
			else FONT_XIP="$addr"; export fontxip_addr="$addr"; break; fi
		fi
	done
fi


# LG rc.local
if [ "${APP_XIP}" != "" ] && [ "${APP_XIP}" != "0x0" ]; then
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t cramfs lgapp /mnt/lg/lgapp -o "physaddr=${APP_XIP}"
	else # S7
		mount -t cramfs lgapp_xip /mnt/lg/lgapp -o "physaddr=${APP_XIP}"
	fi
else
	echo 'rcS-lginit: squashfs /mnt/lg/lgapp'
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t squashfs /dev/mtdblock8 /mnt/lg/lgapp
	else # S7
		mount -t squashfs /dev/mtdblock21 /mnt/lg/lgapp
	fi
fi

if [ "${FONT_XIP}" != "" ] && [ "${FONT_XIP}" != "0x0" ]; then
	echo 'rcS-lginit: cramfs lgfont_xip'
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t cramfs lgfont /mnt/lg/res/lgfont -o "physaddr=${FONT_XIP}"
	else # S7
		#mount -t cramfs lgfont_xip /mnt/lg/res/lgfont -o physaddr=0xf100000
		mount -t cramfs lgfont_xip /mnt/lg/res/lgfont -o "physaddr=${FONT_XIP}"
	fi
else
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t squashfs /dev/mtdblock10 /mnt/lg/res/lgfont
	else # S7
		mount -t squashfs /dev/mtdblock18 /mnt/lg/res/lgfont
	fi
fi
