#!/bin/sh
# Source code released under GPL License
# rcS for Saturn6/Saturn7 by mmm4m5m, djpety

[ -n "$1" ] && { echo "rcS-services: $1" > /dev/kmsg; sleep "$1"; }

r=$(pgrep -f '^/mnt/lg/lgapp/RELEASE ' | wc -l)
[ "$r" -lt 2 ] && NOREL=1 || NOREL=''

# environment for services - check /etc/profile (not for RELEASE - outside rcS-lginit-env)
[ -f /etc/TZ ] && export TZ=`cat /etc/TZ`



. /etc/init.d/module boot; #&

if [ -z "$NOREL" ]; then
	. /etc/init.d/rcS-usercall1 call_wait > /dev/kmsg 2>&1; # wait USB (network)
else
	. /etc/init.d/release-mount boot; # init USB (network)
fi

. /etc/init.d/network boot
[ -f /etc/init.d/wireless ] && . /etc/init.d/wireless boot

# services from rootfs (network/wireless is started)
for i in telnetd ntpd dropbear; do
	# TODO: use sym.links /etc/rc.d/[SK]*
	. /etc/init.d/$i boot; #&
done



[ -z "$NOREL" ] && . /etc/init.d/mount wait; # wait for /mnt/usb?/Drive?

. /etc/init.d/mount boot
[ -z "$NOREL" ] &&
	if [ -d /mnt/lg/lginit ]; then # not S6 = S7
		[ -f /etc/init.d/netcast ] && . /etc/init.d/netcast boot
	fi

# services from extroot (usb1/Drive1 is available, ext3/nfs/cifs is mounted)
for i in httpd ftpd djmount; do
	# TODO: use sym.links /etc/rc.d/[SK]*
	. /etc/init.d/$i boot; #&
done

# auto_start.sh and 'auto update' LGMOD config from USB
for i in lgmod; do
	. /etc/init.d/$i boot
done
