#!/bin/sh
# Source code released under GPL License
# rcS for Saturn6/Saturn7 by mmm4m5m

if [ -d /mnt/lg/lginit ]; then # not S6 = S7
	RELBIN='^/mnt/lg/lgapp/RELEASE '; # pgrep
else
	RELBIN='./RELEASE'; # pgrep
fi

mountall() {
	D=$(stat -c%D /mnt/usb1)
	. /etc/init.d/rcS-funcs; # load_modules
	for j in 1 2; do
		[ $j = 1 ] && J=a; [ $j = 2 ] && J=b
		for i in 1 2 3 4; do
			ARG="noatime /dev/sd$J$i"; arg="/mnt/usb$j/Drive$i"
			d=$(stat -c%D $arg); [ "$d" = "$D" ] || continue
			echo "release-mount: $1 $ARG $arg ..."
			mount -t vfat -o iocharset=utf8,shortname=mixed,$ARG $arg ||
				mount -t ntfs -o $ARG $arg ||
				{ load_modules "release-mount: $1" ext3 && mount -t ext3 -o $ARG $arg; } ||
				mount -o $ARG $arg
		done
	done
}

START() {
	D=$(stat -c%D /mnt/usb1)
	for j in 1 2; do
		[ $j = 1 ] && J=a; [ $j = 2 ] && J=b
		for i in 1 2 3 4; do
			ARG="noatime /dev/sd$J$i"; arg="/mnt/usb$j/Drive$i"
			d=$(stat -c%D $arg); [ "$d" = "$D" ] || continue
			echo "release-mount: $1 $ARG $arg ..."
			mount -t vfat -o iocharset=utf8,shortname=mixed,$ARG $arg ||
				mount -t ntfs -o $ARG $arg
		done
	done
}

boot() {
	{
	. /etc/init.d/rcS-usercall1 call_and_wait
	START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	pgrep -f "$RELBIN" && { echo 'release-mount: Already started'; return 1; }
	. /etc/init.d/rcS-usercall1 call_wait
	START "$@"
}

stop() {
	#pgrep -f "$RELBIN" && { echo 'release-mount: Already started'; return 1; }
	sync
	ARG=''; [ "$2" != '-f' ] && [ "$2" != '-r' ] || ARG="$2"
	D=$(stat -c%D /mnt/usb1)
	for j in 2 1; do
		for i in 4 3 2 1; do
			arg=/mnt/usb$j/Drive$i
			d=$(stat -c%D $arg); [ "$d" = "$D" ] && continue
			echo "release-mount: $1 $ARG $arg ..."
			umount $ARG $arg
		done
	done
}

restart() {
	stop "$@"; START "$@"
}

case "$1" in
	mountall)	mountall "$@";;
	boot)		boot "$@";;
	start)		start "$@";;
	stop)		stop "$@";;
	restart)	restart "$@";;
	*)			echo "Usage: $0 mountall|start|stop|restart [-f|-r]"; exit 1
esac
