#!/bin/sh
# http://openlgtv.org.ru - LGMOD
# Copyright 2009 Vuk
# Copyright 2010 Arno1
# Copyright 2011 lprot, mmm4m5m

CFG_DIR="/mnt/lg/user/lgmod"

START() {
	echo "djmount: $@"
	insmod /lib/modules/fuse.ko
	djmount -f -o kernel_cache `cat $CFG_DIR/upnp` &
}

boot() {
	{
	# Launch UPnP client
	[ -e $CFG_DIR/upnp ] && START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	pgrep -f '^djmount' && { echo 'djmount: Already started'; return 1; }
	START "$@"
}

stop() {
	pkill -f '^djmount'
}

restart() {
	stop "$@"; START "$@"
}

case "$1" in
	boot)		boot "$@";;
	start)		start "$@";;
	stop)		stop "$@";;
	restart)	restart "$@";;
	*)			echo "Usage: $0 start|stop|restart"; exit 1
esac
