#!/bin/sh

CFG_DIR="/mnt/lg/user/lgmod"
MODULES_SH="$CFG_DIR/module.sh"
MODULES_DIR=/lib/modules
P_SH="$CFG_DIR/patch.sh"
SRC_DIR="/mnt/lgmod"
S_SH="$CFG_DIR/auto_stop.sh"

do_boot() {
	[ -d /dev/shm/upload ] || mkdir /dev/shm/upload

	# lgmod: rc.sysinit rc.local
	local DEBUG=0
	if [ -e $CFG_DIR/debug ]; then
		echo 'LGMOD: DEBUG!' > /dev/kmsg
		DEBUG=1
		rm $CFG_DIR/debug
		sync
	fi

	# Copy script for modules loading if not exist (first boot)
	if [ ! -e $MODULES_SH ]; then
		echo "LGMOD: Default ${MODULES_SH#*/}" > /dev/kmsg
		cp -a $SRC_DIR/default-module.sh $MODULES_SH
		sync
	fi

	# Copy default patch script
	if [ ! -e $P_SH ]; then
		echo "LGMOD: Default ${P_SH#*/}" > /dev/kmsg
		cp -a $SRC_DIR/default-patch.sh $P_SH
		sync
	fi

	# Load modules with modules script
	echo "LGMOD: Starting ${MODULES_SH#*/}" > /dev/kmsg
	(cd $MODULES_DIR; $MODULES_SH)

	# Launch patch script
	echo "LGMOD: Starting ${P_SH#*/} - patchwork time" > /dev/kmsg
	$P_SH

	exit $DEBUG
}

do_shutdown() {
	# lgmod: /etc/init.d/rcS
	echo 'LGMOD: Starting auto_stop.sh'
	echo 'LGMOD: Starting auto_stop.sh' > /dev/kmsg
	exec /bin/sh $S_SH
}

do_start() {
	if [ ! -h /mnt/lg/cmn_data/resolv.conf ]; then
		rm /mnt/lg/cmn_data/resolv.conf
		ln -s /tmp/resolv.conf /mnt/lg/cmn_data/
	fi

	# lgmod: /etc/init.d/rcS
	exec /etc/lgmod.sh
}

do_stop() {
	killall udhcpc
	killall ntpd
	killall telnetd
	killall tcpsvd
	killall djmount
	killall httpd
}

case "$1" in
	boot)
		do_boot
		;;
	shutdown)
		do_shutdown
		;;
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		do_stop
		do_start
		;;
	*)
		echo "Usage: $0 {boot|start|stop|restart}"
		exit 1
esac
