#!/bin/sh
# LGMOD version ver=
# http://openlgtv.org.ru - LGMOD
# Copyright 2009 Vuk
# Copyright 2010 Arno1
# Copyright 2011 lprot, mmm4m5m

CFG_DIR="/mnt/lg/user/lgmod"
A_SH=$CFG_DIR/auto_start.sh
S_SH=$CFG_DIR/auto_stop.sh

config() {
	NETCONFIG=$CFG_DIR/network
	HTTPD_CONF=$CFG_DIR/httpd.conf
	MODULES_SH=$CFG_DIR/module.sh
	P_SH=$CFG_DIR/patch.sh
	sync=''

	{
	echo "lgmod: $@"
	for k in 1 2 3 4 5 6 7 8 9 0; do
		D=$(stat -c%D /mnt/usb1 /mnt/usb1/Drive1); D=$(echo $D); d="${D%% *}"; D="${D#* }"
		[ "$d" = "$D" ] || break; sleep 3; done

	# Reset all LGMOD configs to default if special file is present on USB drive
	f=/mnt/usb1/Drive1/lgmod_reset_config
	if [ -e $f ]; then
		cp -R $CFG_DIR /mnt/usb1/Drive1; rm -rf $CFG_DIR
		mv $f ${f}_used; sync=1
		echo 'LGMOD: Config folder is copied to the USB drive and deleted'
		#echo 'Rebooting...'; sync; reboot
	fi

	# Create directory for LGMOD configuration files if not exists
	if [ ! -e $CFG_DIR ]; then
		mkdir $CFG_DIR; sync=1
	fi

	# Copy network config file from USB drive if exists to the LGMOD config folder
	f=/mnt/usb1/Drive1/network
	if [ -e $f ]; then
		cp $f $NETCONFIG; dos2unix $NETCONFIG
		mv $f ${f}_used; sync=1
		echo 'LGMOD: Network config file is copied from the USB drive to the LGMOD config folder'
	fi

	# Copy Web UI configuration file from USB drive if exists to the LGMOD config folder
	f=/mnt/usb1/Drive1/httpd.conf
	if [ -e $f ]; then
		cp $f $HTTPD_CONF; dos2unix $HTTPD_CONF
		mv $f ${f}_used; sync=1
		echo 'LGMOD: Web UI config is copied from USB drive to the LGMOD config folder'
	fi

	# Copy autostart script from USB drive if exist
	f=/mnt/usb1/Drive1/auto_start.sh
	if [ -e $f ]; then
		cp $f $A_SH; dos2unix $A_SH
		chmod +x $A_SH
		mv $f ${f}_used; sync=1
		echo 'LGMOD: Autostart script is copied from USB drive to the LGMOD config folder'
	fi

	# Copy autostop script from USB drive if exist
	f=/mnt/usb1/Drive1/auto_stop.sh
	if [ -e $f ]; then
		cp $f $S_SH; dos2unix $S_SH
		chmod +x $S_SH
		mv $f ${f}_used; sync=1
		echo 'LGMOD: Autostop script is copied from USB drive to the LGMOD config folder'
	fi

	# Copy module script from USB drive if exist
	f=/mnt/usb1/Drive1/module.sh
	if [ -e $f ]; then
		cp $f $MODULES_SH; dos2unix $MODULES_SH
		chmod +x $MODULES_SH
		mv $f ${f}_used; sync=1
		echo 'LGMOD: Module script is copied from USB drive to the LGMOD config folder'
	fi

	# Copy patch script from USB drive if exists
	f=/mnt/usb1/Drive1/patch.sh
	if [ -e /mnt/usb1/Drive1/patch.sh ]; then
		cp $f $P_SH; dos2unix $P_SH
		chmod +x $P_SH
		mv $f ${f}_used; sync=1
		echo 'LGMOD: Patch script is copied from USB drive to the LGMOD config folder'
		#echo 'Rebooting...'; sync; reboot
	fi

	[ -n "$sync" ] && sync
	} > /dev/kmsg 2>&1
}

START() {
	SRC_DIR=/home/lgmod

	# Copy default autostart script
	if [ ! -e $A_SH ]; then
		echo "lgmod: Default ${A_SH#*/} ..."
		[ -d "$CFG_DIR" ] || mkdir -p "$CFG_DIR"
		cp -a $SRC_DIR/default-${A_SH#*/} $A_SH; sync
	fi
	# Copy default autostop script
	if [ ! -e $S_SH ]; then
		echo "lgmod: Default ${S_SH#*/} ..."
		[ -d "$CFG_DIR" ] || mkdir -p "$CFG_DIR"
		cp -a $SRC_DIR/default-${S_SH#*/} $S_SH; sync
	fi

	# Launch autostart script
	if [ -x $A_SH ]; then
		echo "lgmod: $@ ${A_SH#*/} ..."
		$A_SH "$@"
	fi
}

boot() {
	{
	START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	START "$@"
}

stop() {
	if [ -x $S_SH ]; then
		echo "lgmod: $@ ${S_SH#*/} ..."
		$S_SH "$@"
	fi
}

restart() {
	stop "$@"; START "$@"
}

case "$1" in
	config)		config "$@";;
	boot)		boot "$@";;
	start)		start "$@";;
	stop)		stop "$@";;
	restart)	restart "$@";;
	*)			echo "Usage: $0 config|start|stop|restart"; exit 1
esac
