#!/bin/sh
# Source code released under GPL License
# rcS for Saturn7 by mmm4m5m

START() {
	for i in 1 2 3 4; do
		for j in 1 2; do
			arg="/mnt/usb$j/Drive$i/LGMOD_S7/contents"
			[ -d "$arg" ] || continue
			echo "netcast-mount: $1 bind $arg"
			mount -o bind "$arg" /mnt/addon/contents
			arg="/mnt/usb$j/Drive$i/LGMOD_S7/cache"
			[ -d "$arg" ] || mkdir -p "$arg"
			mount -o bind "$arg" /mnt/cache
			killall stagecraft
			break 2
		done
	done
}

boot() {
	{
	START "$@"
	} > /dev/kmsg 2>&1
}

start() {
	D=$(stat -c%D /mnt /mnt/cache /mnt/addon /mnt/addon/contents); D=$(echo $D)
	d1="${D%% *}"; D="${D#* }"; d2="${D%% *}"; D="${D#* }"; d3="${D%% *}"; D="${D#* }"
	[ "$d1" != "$d2" ] && [ "$d3" != "$D" ] &&
		{ echo 'netcast-mount: Already started'; return 1; }
	START "$@"
}

stop() {
	sync
	ARG=''; [ "$2" != '-f' ] && [ "$2" != '-r' ] || ARG="$2"
	echo "netcast-mount: $1 $ARG $arg ..."
	umount $ARG /mnt/addon/contents /mnt/cache
}

restart() {
	stop "$@"; START "$@"
}

case "$1" in
	boot)		boot "$@";;
	start)		start "$@";;
	stop)		stop "$@";;
	restart)	restart "$@";;
	*)			echo "Usage: $0 start|stop|restart [-f|-r]"; exit 1
esac
