#!/bin/sh
#
# /etc/init.d/rcK - run once at shutdown

echo 'rcK: shutdown' > /dev/kmsg

/etc/init.d/lgmod shutdown

sync
umount -r /mnt/lg/user
umount -r /mnt/lg/cmn_data

umount -r /mnt/lg/ciplus/authcxt

# LG inittab
#/bin/umount -a -r

exit 0
