#!/bin/sh
#
# /etc/init.d/rcK - run once at shutdown

/etc/init.d/lgmod shutdown

sync

if ! cat /proc/mounts | grep -q ' cramfs '; then
	# LG inittab
	/bin/umount -a -r
elif pgrep -f '^/mnt/lg/lgapp/RELEASE'; then
	# LG inittab
	/bin/umount -a -r
else
	umount -r $(cat /proc/mounts|grep -nv ' cramfs '|sort -nr|cut -d' ' -f2)
fi

echo 'rcK: shutdown DONE'
exit 0
