#!/bin/sh
# Source code released under GPL License
# rcS for Saturn7 by mmm4m5m

f=/mnt/lg/user/mtd10_nvram_auto.gz; F=mtd10_nvram.gz
{
if [ -f $f ]; then
	h=$(hexdump -n64 -e'"%_c"' /dev/mtd10)
	if [ "$h" = $'377*' ]; then
		echo "rcS-nvram: $f > mtd10" && gzip -d -c $f > /dev/mtd10; # restore nvram
	else
		# if not empty show in log - small sleep added for kmsg (?)
		hexdump /dev/mtd10  -vn64 -e'32 "%4_c" "\n"' && sleep 0.1 &&
		hexdump /dev/mtd10  -vn128 -s384 -e'32 "%4_c" "\n"' && sleep 0.1
	fi
fi

for f in /mnt/lg/cmn_data /mnt/lg/user; do
	[ -f $f/$F ] && continue; # TODO: force new backup if...???

	h=$(hexdump -n64 -e'"%_c"' /dev/mtd10)
	[ "$h" = $'377*' ] && { echo 'rcS-nvram: backup: empty'; break; }

	h=$(hexdump -vs1330 -n13 -e'"%_p"' /dev/mtd10)
	touch "/mnt/lg/cmn_data/model.${h%%.*}" "/mnt/lg/user/model.${h%%.*}"; # expose model name

	echo "rcS-nvram: backup: $f/$F"
	cat /dev/mtd10 | gzip -1 > $f/$F; sync; break
done
} >/dev/kmsg 2>&1
