#!/bin/sh
# Source code released under GPL License
# rcS for Satrun7 by mmm4m5m

NOREL="$1"
RBG="$2"
DELAY="$3"
RUN=/mnt/lg/user/lgmod/init/rcS-services

sleep "$DELAY"

[ -f "$RUN" ] && . "$RUN"


/etc/init.d/lgmod boot

CFG_DIR="/mnt/lg/user/lgmod"
MODULES_DIR=/lib/modules
MODULES_SH="$CFG_DIR/module.sh"
A_SH="$CFG_DIR/auto_start.sh"
P_SH="$CFG_DIR/patch.sh"

{
# lgmod: rc.sysinit rc.local
# Load modules with modules script
echo "LGMOD: Starting ${MODULES_SH##*/} ..."
( cd $MODULES_DIR; $MODULES_SH; )

if [ -z "$NOREL" ]; then
	# Launch patch script
	echo "LGMOD: Starting ${P_SH##*/} ... (patchwork time)"
	$P_SH
fi

if [ -z "$NOREL" ]; then
	. /etc/init.d/rcS-usercall1 0 10
	for k in 1 2 3 4 5; do
		D=$(stat -c%D /mnt/usb1 /mnt/usb1/Drive1); D=$(echo $D); d="${D%% *}"; D="${D#* }"
		[ "$d" = "$D" ] || break; sleep 2; done
else
	. /etc/init.d/release-mount
fi

/etc/init.d/lgmod start

# Launch autostart script
echo "LGMOD: Starting ${A_SH##*/} ..."
$A_SH
} > /dev/kmsg 2>&1
