#!/bin/sh
# Source code released under GPL License
# OpenLGTV BCM - lginit as shell script by xeros
# Modified for Saturn7 by mmm4m5m

{
CMD=''

APP_XIP=''; addr="$appxip_addr"
ADDR=''
for i in 1 2 3 4; do
	[ -z "$CMD" ] && [ $i != 1 ] && [ $i != 2 ] && CMD=" $(cat /proc/cmdline) "

	if   [ $i = 2 ]; then addr="${CMD#*appxip_addr=}"; addr="${addr%% *}"
	elif [ $i = 3 ]; then addr="${CMD##*appxip_addr=}"; addr="${addr%% *}"
	else addr=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/appxip_addr=/ { print $2 }'`; fi

	[ $i != 1 ] && [ "$addr" = "$ADDR" ] && continue; ADDR="$addr"

	if [ "$addr" != "" ] && [ "$addr" != "0x0" ]; then
		cramfs_magic=`devmem $((addr+16)) 64`
		release_magic=`devmem $((addr+1024*4)) 32`
		if [ "$cramfs_magic" != '0x73736572706D6F43' ]; then
			echo "rcS-cramfs($i): Error: cramfs lgapp_xip - wrong magic"
		elif [ "$release_magic" != '0x464C457F' ]; then
			echo "rcS-cramfs($i): Error: cramfs RELEASE - wrong magic"
		else APP_XIP="$addr"; export appxip_addr="$addr"; break; fi
	fi
done

FONT_XIP=''; addr="$fontxip_addr"
ADDR=''
for i in 1 2 3 4; do
	[ -z "$CMD" ] && [ $i != 1 ] && [ $i != 2 ] && CMD=" $(cat /proc/cmdline) "

	if   [ $i = 2 ]; then addr="${CMD#*fontxip_addr=}"; addr="${addr%% *}"
	elif [ $i = 3 ]; then addr="${CMD##*fontxip_addr=}"; addr="${addr%% *}"
	else addr=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/fontxip_addr=/ { print $2 }'`; fi

	[ $i != 1 ] && [ "$addr" = "$ADDR" ] && continue; ADDR="$addr"

	if [ "$addr" != "" ] && [ "$addr" != "0x0" ]; then
		cramfs_magic=`devmem $((addr+16)) 64`
		if [ "$cramfs_magic" != '0x73736572706D6F43' ]; then
			echo "rcS-cramfs($i): Error: cramfs lgfont_xip - wrong magic"
		else FONT_XIP="$addr"; export fontxip_addr="$addr"; break; fi
	fi
done
} > /dev/kmsg 2>&1
