#!/bin/sh
# Source code released under GPL License
# rcS for Satrun7 by mmm4m5m

NOREL="$1"; RBG="$2"; DELAY="$3"

[ -n "$DELAY" ] && sleep "$DELAY"


. /etc/init.d/release-patch boot; #&
. /etc/init.d/module boot; #&


if [ -n "$NOREL" ]; then
	#. /etc/init.d/rcS-usercall1 0 10 > /dev/kmsg 2>&1; # init USB (network)
	. /etc/init.d/release-mount boot
fi

. /etc/init.d/network boot


# TODO: symlinks /etc/rc.d/[SK]*
for i in telnetd dropbear ntpd httpd ftpd djmount; do
	. /etc/init.d/$i boot; #&
done


[ -n "$NOREL" ] && . /etc/init.d/lgmod config; # wait for Drive1

for i in mount lgmod; do
	. /etc/init.d/$i boot
done

[ -z "$NOREL" ] && . /etc/init.d/netcast-mount boot
