#!/bin/sh
# Source code released under GPL License
# OpenLGTV BCM - lginit as shell script by xeros
# Modified for Saturn7 by mmm4m5m

TFS=/tmp/lgmod/tmpfs; STO=/tmp/lgmod/Storage

OVERLAY="$1"

# LG rc.local
#HOST_NAME=`cat /proc/cmdline | awk 'BEGIN { RS="[ ]"; FS="="; } /host=/ { print $2 } END {}'`

#[ -z "$host" ] && { cmd=" $(cat /proc/cmdline) "; host="${cmd#*host=}"; export host="${host%% *}"; }
#hostname $host


{
mount -t jffs2 /dev/mtdblock9 /mnt/lg/cmn_data -o noatime ||
	echo 'rcS-lginit: help: flash_eraseall -j /dev/mtd9'
#mount -t jffs2 /dev/mtdblock11 /mnt/lg/user -o noatime ||
#	echo 'rcS-lginit: help: flash_eraseall -j /dev/mtd11'


[ -z "$OVERLAY" ] && { d=/lgsw; mkdir -p "$TFS$d"; mount -o bind "$TFS$d" "$d"; }

# LG rc.sysinit
mount -a

d=/usr/local; mkdir -p "$STO$d"; lsmod | grep -q '^mini_fo ' && 
	mount -t mini_fo -o base="$d",sto="$STO$d" "mini$d" "$d" ||
	{ d="$d/etc"; mkdir -p "$TFS$d"; mount -o bind "$TFS$d" "$d"; }
} > /dev/kmsg 2>&1
