#!/bin/sh
# Source code released under GPL License
# rcS for Saturn6/Saturn7 by mmm4m5m

if [ ! -d /mnt/lg/lginit ]; then # S6
	appxip_addr=`cat /proc/xipfs`
	fontxip_addr=`cat /proc/fontxipfs`
fi


if [ "$1" != 1 ]; then
	# LG rc.local
	if [ ! -d /mnt/lg/lginit ]; then # S6
		APP_XIP="$appxip_addr"
		FONT_XIP="$fontxip_addr"
	else # S7
		APP_XIP=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/appxip_addr=/ { print $2 }'`
		FONT_XIP=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/fontxip_addr=/ { print $2 }'`
	fi
else
	CMD=''

	APP_XIP=''; addr="$appxip_addr"; ADDR=''
	for i in 1 2 3 4; do
		[ -z "$CMD" ] && [ $i != 1 ] && [ $i != 2 ] && CMD=" $(cat /proc/cmdline) "
		if   [ $i = 2 ]; then addr="${CMD#*appxip_addr=}"; addr="${addr%% *}"
		elif [ $i = 3 ]; then addr="${CMD##*appxip_addr=}"; addr="${addr%% *}"
		else addr=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/appxip_addr=/ { print $2 }'`; fi
		[ $i != 1 ] && [ "$addr" = "$ADDR" ] && continue; ADDR="$addr"
		if [ "$addr" != "" ] && [ "$addr" != "0x0" ]; then
			cramfs_magic=`devmem $((addr+16)) 64`
			release_magic=`devmem $((addr+1024*4)) 32`
			if [ "$cramfs_magic" != '0x73736572706D6F43' ]; then
				echo "rcS-cramfs($i): Error: cramfs lgapp_xip - wrong magic"
			elif [ "$release_magic" != '0x464C457F' ]; then
				echo "rcS-cramfs($i): Error: cramfs RELEASE - wrong magic"
			else APP_XIP="$addr"; export appxip_addr="$addr"; break; fi
		fi
	done

	FONT_XIP=''; addr="$fontxip_addr"; ADDR=''
	for i in 1 2 3 4; do
		[ -z "$CMD" ] && [ $i != 1 ] && [ $i != 2 ] && CMD=" $(cat /proc/cmdline) "
		if   [ $i = 2 ]; then addr="${CMD#*fontxip_addr=}"; addr="${addr%% *}"
		elif [ $i = 3 ]; then addr="${CMD##*fontxip_addr=}"; addr="${addr%% *}"
		else addr=`cat /proc/cmdline | awk -v RS='[ ]' -F= '/fontxip_addr=/ { print $2 }'`; fi
		[ $i != 1 ] && [ "$addr" = "$ADDR" ] && continue; ADDR="$addr"
		if [ "$addr" != "" ] && [ "$addr" != "0x0" ]; then
			cramfs_magic=`devmem $((addr+16)) 64`
			if [ "$cramfs_magic" != '0x73736572706D6F43' ]; then
				echo "rcS-cramfs($i): Error: cramfs lgfont_xip - wrong magic"
			else FONT_XIP="$addr"; export fontxip_addr="$addr"; break; fi
		fi
	done
fi


# LG rc.local
if [ "${APP_XIP}" != "" ] && [ "${APP_XIP}" != "0x0" ]; then
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t cramfs lgapp /mnt/lg/lgapp -o "physaddr=${APP_XIP}"
	else # S7
		mount -t cramfs lgapp_xip /mnt/lg/lgapp -o "physaddr=${APP_XIP}"
	fi
else
	echo 'rcS-lginit: squashfs /mnt/lg/lgapp'
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t squashfs /dev/mtdblock8 /mnt/lg/lgapp
	else # S7
		mount -t squashfs /dev/mtdblock21 /mnt/lg/lgapp
	fi
fi

if [ "${FONT_XIP}" != "" ] && [ "${FONT_XIP}" != "0x0" ]; then
	echo 'rcS-lginit: cramfs lgfont_xip'
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t cramfs lgfont /mnt/lg/res/lgfont -o "physaddr=${FONT_XIP}"
	else # S7
		#mount -t cramfs lgfont_xip /mnt/lg/res/lgfont -o physaddr=0xf100000
		mount -t cramfs lgfont_xip /mnt/lg/res/lgfont -o "physaddr=${FONT_XIP}"
	fi
else
	if [ ! -d /mnt/lg/lginit ]; then # S6
		mount -t squashfs /dev/mtdblock10 /mnt/lg/res/lgfont
	else # S7
		mount -t squashfs /dev/mtdblock18 /mnt/lg/res/lgfont
	fi
fi
