#!/bin/sh
# Source code released under GPL License
# OPENRELEASE by rtokarev is licensed under BSD License
# rcS for Saturn6/Saturn7 by mmm4m5m

# Usage:
#	$0 test <MODE>	return true is <MODE> require tmux
#	$0 .... <MODE>	run RELEASE
# unknown MODE=LG	LG default

Action="$1"; Mode=LG
for i in OPENREL-TMUX-PIPE OPENREL-TMUX OPENRELEASE OPENREL-DAEMON TMUX-PIPE TMUX; do
	[ "$2" = $i ] && Mode=$i && break; done
Ropen=1; for i in TMUX-PIPE TMUX LG; do [ "$Mode" = "$i" ] && Ropen='' && break; done
Rtmux=1; for i in OPENRELEASE OPENREL-DAEMON LG; do [ "$Mode" = "$i" ] && Rtmux='' && break; done
[ "$Action" = test ] && { [ -n "$Rtmux" ]; return; exit; }

Rcmd=/mnt/lg/lgapp/RELEASE; Rarg='0'; Rpipe=/tmp/RELEASE.out
Ocfg='-c /etc/openrelease/openrelease.cfg'
#[ "$Mode" = OPENREL-DAEMON ] && Ocfg='-c /etc/openrelease/openrel-daemon.cfg'
Oarg='-l /tmp/openrelease.log -vvv'; OLIB=libopenrelease.so

if [ ! -d /mnt/lg/lginit ]; then # S6
	cd /; #??? Rcmd=./RELEASE; Rarg=''; cd /mnt/lg/lgapp
else # S7
	cd /; # /mnt/lg/lginit
fi

Ocmd="export LD_PRELOAD=$OLIB; exec $Rcmd $Ocfg $Oarg -- $Rarg"
hint="$Ocmd"; [ "$Mode" = OPENREL-DAEMON ] && hint="LD_PRELOAD=$OLIB $Rcmd $Ocfg -d $Oarg -- $Rarg" ||
	for i in TMUX-PIPE TMUX LG; do [ "$Mode" = "$i" ] && hint="$Rcmd $Rarg" && break; done
echo 'rcS-release: help: $ call debug_os_shell+0xb0' > /dev/kmsg
echo "rcS-release: Starting RELEASE $Mode ($hint) ..." > /dev/kmsg


if [ -n "$Rtmux" ]; then
	Tcmd="tmux pipe-pane 'cat >> $Rpipe'; tmux detach-client; echo '$Mode PIPE: $Rpipe'"
	{ if [ "$Mode" = OPENREL-TMUX-PIPE ]; then
		COLUMNS=300 tmux new-session -s LGMOD -n RELEASE "$Tcmd; $Ocmd"
	elif [ "$Mode" = OPENREL-TMUX ]; then
		COLUMNS=300 tmux new-session -d -s LGMOD -n RELEASE "echo '$Mode'; $Ocmd"
	elif [ "$Mode" = TMUX-PIPE ]; then
		COLUMNS=300 tmux new-session -s LGMOD -n RELEASE "$Tcmd; exec $Rcmd $Rarg"
	elif [ "$Mode" = TMUX ]; then
		COLUMNS=300 tmux new-session -d -s LGMOD -n RELEASE "echo '$Mode'; exec $Rcmd $Rarg"
	fi; } > /dev/kmsg 2>&1
elif [ "$Mode" = OPENRELEASE ]; then
	LD_PRELOAD=$OLIB exec $Rcmd $Ocfg $Oarg -- $Rarg
	return 1; exit 1
elif [ "$Mode" = OPENREL-DAEMON ]; then
	LD_PRELOAD=$OLIB $Rcmd $Ocfg -d $Oarg -- $Rarg; # > /dev/kmsg 2>&1
else
	exec $Rcmd $Rarg
	return 1; exit 1
fi

return 0; exit 0
