#!/bin/sh
# Source code released under GPL License
# rcS for Satrun7 by mmm4m5m

[ -n "$1" ] && sleep "$1"

r=$(pgrep -f '^/mnt/lg/lgapp/RELEASE' | wc -l)
[ "$r" -lt 2 ] && NOREL=1 || NOREL=''


. /etc/init.d/module boot; #&

if [ -z "$NOREL" ]; then
	. /etc/init.d/rcS-usercall1 call_wait > /dev/kmsg 2>&1; # wait USB (network)
else
	. /etc/init.d/release-mount boot; # init USB (network)
fi

. /etc/init.d/network boot

for i in telnetd dropbear ntpd httpd ftpd djmount; do
	# TODO: use sym.links /etc/rc.d/[SK]*
	. /etc/init.d/$i boot; #&
done


[ -z "$NOREL" ] && . /etc/init.d/mount wait; # wait for Drive1
. /etc/init.d/mount boot
[ -z "$NOREL" ] && . /etc/init.d/netcast boot

for i in lgmod; do
	. /etc/init.d/$i boot
done
