#!/bin/sh
# /etc/profile: system-wide .profile file for the Bourne shells

echo "Processing /etc/profile ..."
#export PATH=$PATH:/home

alias dir="ls -al"
alias ll="ls -al"
#alias c.="cd .."
#alias c..="cd ../.."
#alias c...="cd ../../.."

#cp /etc/*.sh /lgsw/
cd /lgsw

#echo -ne "\nDone\n\n"


# profile for Saturn7 by mmm4m5m

# env: sh from init (putty)
#TERM=vt102
#PATH=/sbin:/usr/sbin:/bin:/usr/bin
#USER=root
#HOME=/
#host=saturn7
#ramdisk=0
#ip=165.186.175.92:192.168.0.1:192.168.0.10:192.168.0.1:255.255.255.0
#appxip_addr=0x6e00000
#fontxip_addr=0x0
#xipfs=18
#memsize=128
#boot1stver=3.00.01
#boot2ndver=0.01.16
#start_kernel=1453

# env: ssh
#TERM=xterm; # detected?
#PATH=/sbin:/usr/sbin:/bin:/usr/bin; # not exported?
#USER=root
#HOME=/mnt/lg/user/root
#SHELL=/bin/sh
#LOGNAME=root

# env: telnet - from rcS-lginit
#TERM=vt100
#PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
#LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:/mnt/addon/lib:/mnt/addon/stagecraft/lib
#USER=root
#HOME=/mnt/lg/user/root
#SHELL=/bin/sh
#host=saturn7
#ramdisk=0
#ip=165.186.175.92:192.168.0.1:192.168.0.10:192.168.0.1:255.255.255.0
#appxip_addr=0x6e00000
#fontxip_addr=0x0
#xipfs=18
#memsize=128
#boot1stver=3.00.01
#boot2ndver=0.01.16
#start_kernel=1454
#LOG_CALLER=NO
#OSAMEM_SIZE=0x200000
#LOAD_SYM=1
#HOOK_SEGV=YES
#IS_NFS=NO
#ADDON_SYS_PATH=/mnt/addon
#ADDON_RES_PATH=/mnt/addon/res
#ADDON_APP_CTRL=addon_mgr
#ADDON_APP_BATCH_LIST=addon_mgr.bat
#FLASH_APP_NAME=/mnt/addon/stagecraft/bin/stagecraft
#FLASH_EMANUAL_PATH=/mnt/addon/contents/emanual/emmanager.swf

export HOME=/mnt/lg/user/root

. /etc/init.d/rcS-lginit-env; # LG: env

. /etc/init.d/rcS-services-env

alias mounts='cat /proc/mounts'
alias dropc='echo 3 > /proc/sys/vm/drop_caches && free'

if [ -z "$TMUX" ]; then
	if [ -z "$TERM" ] || [ "$TERM" = vt100 ]; then
		alias tmux='TERM=linux tmux'
		alias tma='TERM=linux tmux attach-session'
	else
		alias tma='tmux attach-session'
	fi
fi

alias Dfb='mount -o bind /mnt/lg/user/extroot/usr/local /usr/local'
#Extdfb() {
#	local i D d=/mnt/lg/user/extroot; rm -r $d/*
#	(cd $d/ && tar xzvf /mnt/usb1/Drive1/LG_DTV/lgmod_S7_extroot.tar.gz || exit
#		D=/usr/local; f=$d$D/etc/directfbrc; mkdir -p $d$D/etc
#		for i in `find $D \! -type d`; do [ -e $d$i ] && mv $d$i $d$i~; cp -a $i $d$i; done
#		sed -i -e 's/no-cursor/cursor-updates\nno-linux-input-grab/' $f)
#}

#Exroot() {
#	local d=/mnt/lg/user/extroot; rm -r $d/*
#	(cd $d/ && tar xzvf /mnt/usb1/Drive1/LG_DTV/lgmod_S7_extroot.tar.gz)
#}

MODEL=`echo /mnt/lg/user/model.*`
[ -f "$MODEL" ] && export MODEL="${MODEL#*model.}" || MODEL=''

alias Rstart='/etc/init.d/release start'
Rtell() {
	local f=/tmp/openrelease.in C="$1"; shift
	if [ -e $f ]; then echo -n "$C" > $f
	else tmux send -t RELEASE "$@"; fi
}

Rdpass() {
	[ -n "$MODEL" ] || return; local C="d ${MODEL}elqjrm"
	Rtell "`echo`$C`echo`" C-M "$C" C-M
}
Revent() {
	[ -n "$MODEL" ] || return; local C="d ${MODEL}elqjrm"
	Rtell "`echo`$C`echo`" C-M "$C" C-M; sleep 0.2; Rtell x x
}

#alias Rgame='C="call UI_CONTENTSLINK_CreateWindow"; Rtell "`echo`$C`echo`" C-M "$C" C-M'
alias Rtail='tail -n+1 -F /tmp/RELEASE.out /tmp/openrelease.out /tmp/openrelease.log'
Ropen() {
	local F="/tmp/openrelease.log /tmp/openrelease.out"; (tail -F $F &)
	(trap "pkill -f \"tail -F $F\"; exit" INT; cat >/tmp/openrelease.in)
}

[ -f /mnt/lg/cmn_data/profile ] && . /mnt/lg/cmn_data/profile
