#!/bin/sh
# /etc/profile: system-wide .profile file for the Bourne shells

echo "Processing /etc/profile ..."
#export PATH=$PATH:/home

alias dir="ls -al"
alias ll="ls -al"
#alias c.="cd .."
#alias c..="cd ../.."
#alias c...="cd ../../.."

#cp /etc/*.sh /lgsw/
cd /lgsw

#echo -ne "\nDone\n\n"


# profile for Saturn7 by mmm4m5m

# env: sh from init (putty)
#TERM=vt102
#PATH=/sbin:/usr/sbin:/bin:/usr/bin
#USER=root
#HOME=/
#host=saturn7
#ramdisk=0
#ip=165.186.175.92:192.168.0.1:192.168.0.10:192.168.0.1:255.255.255.0
#appxip_addr=0x6e00000
#fontxip_addr=0x0
#xipfs=18
#memsize=128
#boot1stver=3.00.01
#boot2ndver=0.01.16
#start_kernel=1453

# env: ssh
#TERM=xterm; # detected?
#PATH=/sbin:/usr/sbin:/bin:/usr/bin; # not exported?
#USER=root
#HOME=/mnt/lg/user/root
#SHELL=/bin/sh
#LOGNAME=root

# env: telnet - from rcS-lginit
#TERM=vt100
#PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
#LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:/mnt/addon/lib:/mnt/addon/stagecraft/lib
#USER=root
#HOME=/mnt/lg/user/root
#SHELL=/bin/sh
#host=saturn7
#ramdisk=0
#ip=165.186.175.92:192.168.0.1:192.168.0.10:192.168.0.1:255.255.255.0
#appxip_addr=0x6e00000
#fontxip_addr=0x0
#xipfs=18
#memsize=128
#boot1stver=3.00.01
#boot2ndver=0.01.16
#start_kernel=1454
#LOG_CALLER=NO
#OSAMEM_SIZE=0x200000
#LOAD_SYM=1
#HOOK_SEGV=YES
#IS_NFS=NO
#ADDON_SYS_PATH=/mnt/addon
#ADDON_RES_PATH=/mnt/addon/res
#ADDON_APP_CTRL=addon_mgr
#ADDON_APP_BATCH_LIST=addon_mgr.bat
#FLASH_APP_NAME=/mnt/addon/stagecraft/bin/stagecraft
#FLASH_EMANUAL_PATH=/mnt/addon/contents/emanual/emmanager.swf

export HOME=/mnt/lg/user/root

. /etc/init.d/rcS-lginit-env; # LG: env

after=/lg/user/extroot; # Note: create a sym.link to USB extroot directory
path=/bin:/sbin:/usr/bin:/usr/sbin; pathl=/usr/local/bin
lib=/lib:/usr/lib; libl=/usr/local/lib:/mnt/addon/lib:/mnt/addon/stagecraft/lib
export PATH="$path:$pathl:$after${path//:/:$after}"
export LD_LIBRARY_PATH="$lib:$libl:$after${lib//:/:$after}"
unset after path pathl lib libl

alias mounts='cat /proc/mounts'
alias dropc='echo 3 > /proc/sys/vm/drop_caches; free'

if [ -z "$TMUX" ]; then
	if [ -z "$TERM" ] || [ "$TERM" = vt100 ]; then
		alias tmux='TERM=linux tmux'
		alias tma='TERM=linux tmux attach-session'
	else
		alias tma='tmux attach-session'
	fi
fi

alias Dfb='d=/mnt/lg/user/extroot && (cd $d && d=usr/local && mount -o bind $d /$d)'
alias Extdfb='d=/mnt/lg/user/extroot; [ -d $d/ ] && (cd $d && rm -r *; \
	tar xzvf /mnt/usb1/Drive1/LG_DTV/lgmod_S7_extroot.tar.gz && d=usr/local && cp -r /$d usr/ && \
	f=$d/etc/directfbrc && sed -i -e "/no-cursor/d" $f && { echo cursor-updates; echo no-linux-input-grab; } >> $f)'

alias Exroot='d=/mnt/lg/user/extroot; [ -d $d/ ] && (cd $d && rm -r *; \
	tar xzvf /mnt/usb1/Drive1/LG_DTV/lgmod_S7_extroot.tar.gz)'
alias Rstart='/etc/init.d/release start'

MODEL=`echo /mnt/lg/user/model.*`; export MODEL=${MODEL#*model.}
alias Rdpass='M=`echo /mnt/lg/user/model.*`; M=${M#*model.}; P="d ${M}elqjrm"; \
	f=/tmp/openrelease.in; [ -e $f ] && { echo; echo "$P"; } > $f || tmux send -t RELEASE C-M "$P" C-M'
alias Revent='f=/tmp/openrelease.in; [ -e $f ] && echo -n x > $f || tmux send -t RELEASE x'
alias Rdevnt='M=`echo /mnt/lg/user/model.*`; M=${M#*model.}; P="d ${M}elqjrm"; \
	f=/tmp/openrelease.in; [ -e $f ] && { echo; echo "$P"; } > $f || tmux send -t RELEASE C-M "$P" C-M \
	sleep 0.2; [ -e $f ] && echo -n x > $f || tmux send -t RELEASE x'

alias Rgame='C="call UI_CONTENTSLINK_CreateWindow"; \
	f=/tmp/openrelease.in; [ -e $f ] && { echo; echo "$C"; } > $f || tmux send -t RELEASE C-M "$C" C-M'
alias Rtail='tail -n+1 -F /tmp/RELEASE.out /tmp/openrelease.out /tmp/openrelease.log'
alias Ropen='(F="/tmp/openrelease.log /tmp/openrelease.out"; (tail -F $F&); trap "pkill -f \"tail -F $F\"; exit" INT; cat >/tmp/openrelease.in)'

[ -f /mnt/lg/cmn_data/profile ] && . /mnt/lg/cmn_data/profile
