#!/bin/sh
# Source code released under GPL License
# lginit/rcS for Saturn7 by mmm4m5m

OUT=/dev/kmsg; [ -e $OUT ] || OUT=/dev/stdout

{
D='/ /proc /sys /tmp'; U=/proc/bus/usb; [ -d $U ] && { D="$D $U"; U=''; }
D=$(stat -c%D $D); D=$(echo $D); d="${D%% *}"; D="${D#* }"
d1="${D%% *}"; D="${D#* }"; d2="${D%% *}"; D="${D#* }"
d3="${D%% *}"; d4="${D#* }"; [ -n "$U" ] && d4="$d"

[ "$d" = "$d1" ] && mount -t proc proc /proc
[ "$d" = "$d2" ] && mount -t sysfs sysfs /sys
[ "$d" = "$d4" ] && mount -t usbfs usbfs /proc/bus/usb
[ "$d" = "$d3" ] && mount -t tmpfs tmpfs /tmp -o size=24M
} > $OUT 2>&1
