<head>
<title>LGMOD 1.6.10</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<style type="text/css">
body { background: #EEEEEF; width: 80%; margin:0 auto; }
body, li, td, div { font: 11px verdana, arial, sans-serif; }
ul { list-style-type: none; }
li { font-size: 10pt; }
i { color: silver; }
p.largefont { text-align: left; font-size: 10pt; font-weight: bold; }

div.pagebody { background: white; padding:16px; border: 1px solid silver; }

div.post { border: 1px solid silver; padding: 1px; margin-bottom: 10px; }
div.posttop { padding: 4px; background: #EEEEEE; }
div.posthead { padding: 4px; background: #EEEEEE; font-weight: bold; text-align: left; font-size: 7pt; }
div.posttext { padding: 4px; background: #F9F9F9; }

div.ok { padding: 1px; background: #EEEEEE;}
div.error { padding: 1px; background: #FFFF77; }

span.small { font-size: 10px; }

#content { margin-bottom: 8px; border: 1px solid silver; padding: 4px; padding-left: 24px; }

#navbar { background: #F9F9F9; border: 1px solid silver; padding: 3px; font-weight: bold; }
#navbar P { padding-left: 2pt; padding-right: 4pt; line-height: 2pt; }
#navbar A:link {color: #4040C0; text-decoration: none }
#navbar A:visited { color: #4030FF; text-decoration: none }
#navbar A:hover   { color: #F04080; text-decoration: none }
#navbar A:active  { color: #000000; background-color: #E0E0E0; text-decoration: none }
#navbar A:focus   { color: #303030; text-decoration: none }

#copyright { text-align: center; font-size: 7pt;}
hrr { visibility: hidden; display: none; }
hr { color: #fafafa; }

table { border-collapse: collapse; }
th { padding: 1px; font-size: 12px; }
</style>
</head>
